export { default as Main } from './Main'
export { default as Catagory } from './Catagory'
export { default as Regist } from './Regist'
export { default as SignUp } from './SignUp'
export { default as MyPage} from './My'
export { default as Unknown} from './Unknown'